### ISSUE TITLE
Зачем нужен slice?

### ISSUE THREAD

**Issue by coursar** [corben-dallas/array#6]
https://github.com/corben-dallas/array/blob/d58b2108e266ff7487e1c1f93a35440c0ba360fc/src/js/lib.js#L26

**Comment by corben-dallas** [comment]
sort меняет первоначальный массив, поэтому сделал копию. потом ее отсортировал методом sort, отсек все лишнее, а потом хотел сравнить с оригиналом

**Comment by coursar** [comment]
ок, на будущее - лучше не использовать для этого slice, будем проходить `Array.from(arr)` или spread: `[...arr]`.
